pipeline {
  agent any
  environment {
    DOCKERHUB_USER = 'adjiyahya'
    DOCKERHUB_CREDS = 'docker-hub-creds'
    PATH = "/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin" // 👈 tambahkan ini
  }
  stages {
    stage('Build & Push UI') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDS) {
            def image = docker.build("${DOCKERHUB_USER}/retail-ui", "./src/ui")
            image.push("latest")
          }
        }
      }
    }
  }
}
